version: '3'
services:

  api_redis:
    container_name: api_redis
    image: redis:6-alpine
    restart: always
    volumes:
      - api_redis_data:/data
    ports:
      - $REDIS_PORT:$REDIS_PORT
    networks:
      - new_admin_panel_sprint_3_app-network

  api_app:
    build:
      context: .
      dockerfile: docker_config/app/Dockerfile
    container_name: api_app
    working_dir: /var/www/api_app
    volumes:
      - ./src:/var/www/api_app
    networks:
      - new_admin_panel_sprint_3_app-network
    env_file:
      - .env

  api_nginx:
    image: nginx:1.21.6-alpine
    container_name: api_nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker_config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker_config/nginx/movies.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api_app
    networks:
      - new_admin_panel_sprint_3_app-network

networks:
  new_admin_panel_sprint_3_app-network:
    external: true
volumes:
  api_redis_data:

